export * from './trucker.component';
export * from './trucker-setting.component';
export * from './trucker-add.component';
export * from './trucker-licence.component';
export * from './trucker-insurance.component';
export * from './trucker-available-shipment.component';
export * from './trucker-shipment-details.component';
export * from './trucker-shipment-details-accepted.component';
export * from './trucker-your-shipments.component';
